# Generated by Django 4.2.21 on 2025-05-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_participante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testSystem.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
