# Generated by Django 4.2.21 on 2025-06-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recomendacion',
        ),
    ]
