# Generated by Django 4.2.21 on 2025-06-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='testSystem.prueba'),
        ),
    ]
