# Generated by Django 4.2.21 on 2025-05-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0002_proyecto_id_participante_alter_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='modulo',
        ),
    ]
