# Generated by Django 4.2.21 on 2025-07-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0002_alter_resultado_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='tipo_prueba',
        ),
        migrations.AddField(
            model_name='resultado',
            name='detalle_probabilidades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
