# Generated by Django 4.2.21 on 2025-07-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0003_remove_resultado_tipo_prueba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
    ]
