# Generated by Django 4.2.21 on 2025-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0003_remove_prueba_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='archivo_csv',
            field=models.FileField(blank=True, null=True, upload_to='csvs/'),
        ),
    ]
