# Generated by Django 4.2.21 on 2025-05-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testSystem', '0004_prueba_archivo_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='clasificacion_ml',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='score_probabilidad_flaky',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='tipo_prueba',
        ),
        migrations.CreateModel(
            name='DetallePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_test', models.CharField(max_length=200)),
                ('tipo_prueba', models.CharField(choices=[('unit', 'Unit'), ('integration', 'Integration'), ('e2e', 'End to End')], max_length=50)),
                ('clasificacion_ml', models.CharField(blank=True, max_length=100, null=True)),
                ('score_probabilidad_flaky', models.FloatField(default=0.0)),
                ('estado', models.BooleanField(default=True)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='testSystem.prueba')),
            ],
        ),
    ]
